insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 첫번째 글을 작성 해 보았다', '유저1', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 두번째 글을 작성 해 보았다', '유저2', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 세번째 글을 작성 해 보았다', '유저3', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 네번째 글을 작성 해 보았다', '유저4', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 다섯번째 글을 작성 해 보았다', '유저5', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 여섯번째 글을 작성 해 보았다', '유저6', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 일곱번째 글을 작성 해 보았다', '유저7', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 여덟번째 글을 작성 해 보았다', '유저8', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 아홉번째 글을 작성 해 보았다', '유저9', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 열번째 글을 작성 해 보았다', '유저10', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 열한번째 글을 작성 해 보았다', '유저11', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 열두번째 글을 작성 해 보았다', '유저12', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 열세번째 글을 작성 해 보았다', '유저13', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 열네번째 글을 작성 해 보았다', '유저14', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 열다섯번째 글을 작성 해 보았다', '유저15', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 열여섯번째 글을 작성 해 보았다', '유저16', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 열일곱번째 글을 작성 해 보았다', '유저17', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 열여덟번째 글을 작성 해 보았다', '유저18', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 열아홉번째 글을 작성 해 보았다', '유저19', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 스무번째 글을 작성 해 보았다', '유저20', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 이십한번째 글을 작성 해 보았다', '유저21', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 이십두번째 글을 작성 해 보았다', '유저22', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 이십세번째 글을 작성 해 보았다', '유저23', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 이십네번째 글을 작성 해 보았다', '유저24', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 이십다섯번째 글을 작성 해 보았다', '유저25', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 이십여섯번째 글을 작성 해 보았다', '유저26', 'Y', 'N', NOW());
insert into post (content, writer, visibility_flag, delete_flag, created_at) values ('오늘의 이십일곱번째 글을 작성 해 보았다', '유저27', 'Y', 'N', NOW());

insert into book (title, author, publisher) values ('소나기', '황순원', '민음사');
insert into book (title, author, publisher) values ('두 번째 산', '조정래', '창비');
insert into book (title, author, publisher) values ('삼국지', '이문열', '민음사');
insert into book (title, author, publisher) values ('백설공주', '남궁석', '아울북');
insert into book (title, author, publisher) values ('아몬드', '손원평', '문학동네');
insert into book (title, author, publisher) values ('부활', '레프 톨스토이', '민음사');
insert into book (title, author, publisher) values ('생각의 탄생', '샘 해리스', '김영사');
insert into book (title, author, publisher) values ('1Q84', '하루키 무라카미', '문학동네');
insert into book (title, author, publisher) values ('행복의 건축가들', '김수현', '더숲');
insert into book (title, author, publisher) values ('비밀의 정원', '한정훈', '창비');
