### 1. 글 조회
GET localhost:8080/post

{
  "content": "오늘의 첫번째 글을 작성 해 보았다",
  "writer": "유저1"
}

### 2. 글 전체 조회
GET localhost:8080/posts

[
  {
    "content": "오늘의 첫번째 글을 작성 해 보았다",
    "writer": "유저1"
  },
  {
    "content": "오늘의 두번째 글을 작성 해 보았다",
    "writer": "유저2"
  }
]

### 3. 글 삭제
DELETE localhost:8080/post?postId=1

