### 글 조회
GET {{url}}/post/2


### 글 전체 조회
GET {{url}}/posts

### 글 페이징 조회
GET {{url}}/post/page?pageNum=1

### 글 추가
POST {{url}}/post
Content-Type: application/json

{
  "content": "오늘의 새로운 글을 작성 해 보았다",
  "writer": "새로운 유저",
  "visibilityFlag" : "VISIBLE"
}


### 글 업데이트
PUT {{url}}/post/1
Content-Type: application/json

{
  "content": "오늘의 수정된 글을 작성 해 보았다",
  "writer": "수정된 유저",
  "visibilityFlag" : "VISIBLE"
}

### 글 삭제
DELETE {{url}}/post/1

